### PR TITLE
Removed callback passed to server start in favor of async. Fixes #2424

### LINKED ISSUE #2424: Incorrect mixed use of "async" and callback in server's `start` method
The `start` method for the server is incorrectly using both the `async` keyword (which uses promises) and a callback, `done`. It seems that this was introduced [here](https://github.com/NetsBlox/NetsBlox/commit/68462d8d8e5ba1e9943f0c88be81a20c218980af#diff-f286c15f5cb962ed226f2aae653ca1cfR283) when the method was changed to async without removing the usage of a callback.

### PR DESCRIPTION
**Pull request by brollb**

### CODE REVIEW

**Comment by hamidzr** [comment]
Thanks

File: src/server/server.js [hunk 1]
```diff
@@ -302,28 +301,22 @@ Server.prototype.start = async function(done) {
...
-            const client = new Client(this._logger, socket);
-            NetworkTopology.onConnect(client);
-        });
-
-        // Enable Vantage
-        if (this.opts.vantage) {
-            new Vantage(this).start(this.opts.vantagePort);
-        }
-        done();
+    this._server = this.app.listen(this.opts.port);
```
Comment (hamidzr) [inline src/server/server.js]: don't we need `await` here?

Comment (brollb) [reply src/server/server.js]: Surprisingly, no. `this.app.listen` returns an express server object even when called without a callback. Errors are thrown as normal if there is an error when trying to start the server (eg, `EADDRINUSE`).
