### PR TITLE
ignore dupe fn warnings during doc build

### LINKED ISSUE #3186: Failing to build docs for NYT Service (suspected bug in the service)
```
Error: failed to compile docs: error: , stderr: /home/brian/projektek/netsblox/src/server/docs/_generated/services/NewYorkTimes/Concepts.rst:15: WARNING: duplicate function description of NewYorkTimes.getArticlesWithConcept, other function in services/NewYorkTimes/Articles
, stdout: Running Sphinx v4.0.2
making output directory... done

```

### PR DESCRIPTION
**Pull request by dragazo**
Closes #3186. Apparently Sphinx has no way to disable duplicate function definition warnings, so this PR just adds filtering so that the build script doesn't consider them to be errors.

### CODE REVIEW

File: bin/build-docs.js [hunk 1]
```diff
@@ -310,4 +311,13 @@ async function compileDocs(services) {
     });
 }
 
+function splitErrors(str) {
+    const important = [];
+    const ignored = [];
+    for (const line of str.split('\n').map(s => s.trim()).filter(s => s.length)) {
```
Comment (brollb) [inline bin/build-docs.js:317]: An alternative way to write this would be:
```javascript
const isImportant = line => !line.includes('WARNING: duplicate function description');
const nonEmptyLines = str.split('\n').map(s => s.trim()).filter(s => s.length);
const [important, ignored] = _.partition(nonEmptyLines, isImportant);
```
Either is fine and you don't need to make any changes but I thought I would mention it since I think `_.partition` is a little more legible. :)

**Review by brollb — APPROVED** [review]
Looks good to me! I added a comment below but it isn't blocking the merge.

File: bin/build-docs.js (hunk 1 above)
Comment (dragazo) [reply bin/build-docs.js]: Yeah, forgot I used the weird ternary thing. I just refactored to use partition, and I pulled out the ignore patterns into a list so we can just add to that in the future.
