### PR TITLE
Use uuid for leader detection. Fixes #1489

### LINKED ISSUE #1489: Incorrect leader detection with same username
When a username is collaborating with him/herself on a project, multiple browsers may think that they are the leader resulting in duplicate action acceptance and synchronization issues.

### PR DESCRIPTION
**Pull request by brollb**

### CODE REVIEW

File: src/client/room.js [hunk 1]
```diff
@@ -961,11 +978,7 @@ function EditRoleMorph(room, role) {
     if (role.users.length) {  // occupied
         // owner can evict collaborators, collaborators can evict guests
 
-        // Check if we are occupying that role already. If not, give the
-        // option for collaborative editing
-        if (role.users.indexOf(this.room.myUserId()) === -1) {
```
Comment (brollb) [inline src/client/room.js]: This was easier to just remove than update. I don't think there is a problem allowing the same user occupy the same role from the room editor

Comment (brollb) [reply src/client/room.js]: Added the functionality back in a simpler way.
